export const transactions = [
  {
    id: "txn_1",
    date: "2024-07-28",
    description: "Payment from John Doe",
    amount: "+$250.00",
    status: "Completed",
    type: "Credit",
    method: "Bank Transfer",
  },
  {
    id: "txn_2",
    date: "2024-07-27",
    description: "Online Shopping",
    amount: "-$75.50",
    status: "Completed",
    type: "Debit",
    method: "Credit Card",
  },
  {
    id: "txn_3",
    date: "2024-07-26",
    description: "Subscription Fee",
    amount: "-$12.00",
    status: "Pending",
    type: "Debit",
    method: "PayPal",
  },
  {
    id: "txn_4",
    date: "2024-07-25",
    description: "Refund from Amazon",
    amount: "+$30.00",
    status: "Completed",
    type: "Credit",
    method: "Credit Card",
  },
  {
    id: "txn_5",
    date: "2024-07-24",
    description: "Grocery Store",
    amount: "-$54.30",
    status: "Failed",
    type: "Debit",
    method: "Debit Card",
  },
];